version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phpsample
      MYSQL_USER: phpsample
      MYSQL_PASSWORD: phpsample
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/code

    depends_on:
      - php
  php:
    image: php:fpm
    volumes:
      - .:/code
    depends_on:
      - db
volumes:
  dbdata: