<?php include TEMPLATES_DIR . '/layouts/header.phtml';?>

<div class="container col-sm-3">
    <span class="container" style="text-align: center;"><h2>Add User to DB</h2></span>

    <form action="/user/add" target="_self" method="POST">
        <div class="form-group">
            <label for="exampleInputEmail1">Name</label>
            <input type="text" class="form-control" id="name" name="name" aria-describedby="nameHelp" placeholder="Enter name">
            <small id="nameHelp" class="form-text text-muted">We'll never share your name with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label for="age">Age</label>
            <input type="text" class="form-control" id="age" name="age" placeholder="Age">
        </div>
        <div class="form-group">
            <label for="address">Address</label>
            <input type="text" class="form-control" id="address" name="address" placeholder="Input Address">
        </div>
        <button type="submit" class="btn btn-success btn-lg btn-block" >Submit</button>
    </form>

</div>

<?php include TEMPLATES_DIR . '/layouts/footer.phtml';?>
