<?php include TEMPLATES_DIR . '/layouts/header.phtml';?>

<div class="container">
    <h2> INDEX</h2>
    <?php if (!empty($data)) {
        foreach ($data as $key => $value):?>

        <!-- Project One -->
        <div class="row">

            <div class="col-md-5">
                <p><?= $value['message'];?></p>
                <a class="btn btn-primary" href="<?= $value['id'];?>">Читать</a>
            </div>
        </div>
        <!-- /.row -->

        <hr/>
        <?php endforeach;
    } ?>

</div>

<?php include TEMPLATES_DIR . '/layouts/footer.phtml';?>
