<?php include TEMPLATES_DIR . '/layouts/header.phtml';?>

<div class="container">
        <h1> 404</h1>
<h2>Page not found!</h2>

    <pre>
    ______
    / ____/___  ____ ___  ____  ____  ________  _____
    / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
    / /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
    \____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
    /_/

</pre>
</div>

<?php include TEMPLATES_DIR . '/layouts/footer.phtml';?>