<?php include TEMPLATES_DIR . '/layouts/header.phtml';?>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <div class="container">
        <h2>Users in Db</h2>
            <hr/>
            <div class="row">
                <div class="col">
                    <p>Name</p>
                </div>
                <div class="col">
                    <p>Age</p>
                </div>
                <div class="col">
                    <p>Emali</p>
                </div>
                <div class="col">
                    <p>Address</p>
                </div>
                <div class="col">

                </div>
                <div class="col">

                </div>
            </div>
        <hr/>
        <?php if (!empty($data)) {
            foreach ($data as $key => $value):?>

                <!-- Project One -->
                <div class="row">
                    <div class="col">
                        <p><?= $value['name'];?></p>
                    </div>
                    <div class="col">
                        <p><?= $value['age'];?></p>
                    </div>
                    <div class="col">
                        <p><?= $value['email'];?></p>
                    </div>
                    <div class="col">
                        <p><?= $value['address'];?></p>
                    </div>
                    <div class="col">
                        <a class="btn btn-primary" href="#" id="updateUser"  data-toggle="modal" data-id="<?= $value['id']?>" data-target="#modal-user">Edit</a>
                    </div>
                    <div class="col">
                        <a class="btn btn-primary" href="/user/delete?id=<?= $value['id']?>">Delete</a>
                    </div>
                </div>

                <hr/>
            <?php endforeach;
        } ?>

    </div>


<?php include TEMPLATES_DIR . '/layouts/footer.phtml';?>

<script type="application/javascript">
    let upd = document.getElementById('updateUser');
    const handle = () => {
        const modal = document.getElementById('modal-body');
        modal.innerHTML = '';
        const div = document.createElement('div');
        div.innerHTML = `<tr><td>Huy</td></tr>`;

        modal.append(div);
    }
    upd.addEventListener('click', handle);

    $('#modal-body').on('click', function () {
        alert('click');
    })
</script>

<div class="modal" tabindex="-1" role="dialog" id="modal-user">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="modal-body" class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary">Save changes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

